### ISSUE TITLE
False positive with private fields

### ISSUE THREAD

**Issue by maratori** [mbilski/exhaustivestruct#1]
I can't use `exhaustivestruct` in golangci-lint v1.32.0 because of false positives.
`protoc` generates structs with private fields which can't  and should not be initialised.
For example:
```go
type MyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	...
}
```
Linter complains about those fields.

**Comment by mbilski** [comment]
Thanks for reporting it. I fixed it, now it ignores private fields https://github.com/mbilski/exhaustivestruct/commit/b2c70e3b8ad5874e1504ebb9c8401b4a989e0f5a
